In [1]:
import torch
torch.__version__

'2.2.0'

In [3]:
#scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
#Get the number from within any tensor
scalar.item()

8

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#matrix
matrix = torch.tensor([[7,8],[8,9]])
matrix

tensor([[7, 8],
        [8, 9]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [16]:
#tensor
TENSOR = torch.tensor([[[5,6,7],[4,4,2],[4,2,6]]])
TENSOR

tensor([[[5, 6, 7],
         [4, 4, 2],
         [4, 2, 6]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [4]:
#random_tensors
random_tensor = torch.rand(size=(3,4))
random_tensor,random_tensor.dtype

(tensor([[0.5932, 0.0276, 0.6458, 0.8037],
         [0.7105, 0.5232, 0.9963, 0.3458],
         [0.3064, 0.2725, 0.2221, 0.8729]]),
 torch.float32)

In [7]:
#a random tensor of size (243,212,3)
random_image_size_tensor = torch.rand(size=(243,212,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([243, 212, 3]), 3)

In [10]:
#tensor of all zeroes
zeroes = torch.zeros(size = (3,4))
zeroes,zeroes.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [11]:
#tensor of all ones
ones = torch.ones(size = (3,4))
ones,ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [13]:
#create a range from 0 to 10
zerototen = torch.arange(start=0,end=10,step=1)
zerototen

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])